// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuLOnJAgSZZDypegNseOeeIarAXHZzd0Q',
    appId: '1:894050703795:web:7606e2b23bfaea74bed3c6',
    messagingSenderId: '894050703795',
    projectId: 'vaycayauth',
    authDomain: 'vaycayauth.firebaseapp.com',
    storageBucket: 'vaycayauth.firebasestorage.app',
    measurementId: 'G-MNJRMQBK51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_u3BHG8S3rQm3mTvOsF-cScFw7THzzGM',
    appId: '1:894050703795:android:94b828117a67d016bed3c6',
    messagingSenderId: '894050703795',
    projectId: 'vaycayauth',
    storageBucket: 'vaycayauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2eC36A9c8Du0tst40s7pkmHQgs2FG34w',
    appId: '1:894050703795:ios:64e3c86330a7e83cbed3c6',
    messagingSenderId: '894050703795',
    projectId: 'vaycayauth',
    storageBucket: 'vaycayauth.firebasestorage.app',
    iosBundleId: 'com.example.vaycayApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2eC36A9c8Du0tst40s7pkmHQgs2FG34w',
    appId: '1:894050703795:ios:64e3c86330a7e83cbed3c6',
    messagingSenderId: '894050703795',
    projectId: 'vaycayauth',
    storageBucket: 'vaycayauth.firebasestorage.app',
    iosBundleId: 'com.example.vaycayApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuLOnJAgSZZDypegNseOeeIarAXHZzd0Q',
    appId: '1:894050703795:web:dd7cf5082d3e1aa8bed3c6',
    messagingSenderId: '894050703795',
    projectId: 'vaycayauth',
    authDomain: 'vaycayauth.firebaseapp.com',
    storageBucket: 'vaycayauth.firebasestorage.app',
    measurementId: 'G-FH9YL4G8Q5',
  );
}
